---
mlag_ibgp_peering_vrfs:
  base_vlan: 3000

evpn_rt_type:
  # admin_subfield: < "leaf_asn" | "spine_asn" | "vni" | <0-65535> | <0-4294967295> | default -> "vni" >
  admin_subfield: vni

# DC1 Tenants Networks
# Documentation of Tenant specific information - Vlans/VRFs
tenants:
  # Tenant A Specific Information - VRFs / VLANs
  Tenant_A:
    mac_vrf_vni_base: 10000
    enable_mlag_ibgp_peering_vrfs: true
    vrfs:
      TENANT_A_PROJECT01:
        vrf_vni: 11
        static_routes:
          - destination_address_prefix: 1.1.1.0/24
            gateway: 10.1.10.1
            nodes: ['EAPI-BL01A', 'EAPI-BL01B']
        redistribute_static: true
        svis:
          110:
            name: 'PR01-DEMO'
            tags: ['DC1']
            enabled: true
            ip_address_virtual: 10.1.10.254/24
            # structured_config:
            #   ipv6_enable: < true | false >
            #   ipv6_address: < IPv6_address/Mask >
            #   ipv6_virtual_router_address: < IPv6_address/Mask >

            # igmp_snooping: false
          111:
            name: 'PR01-TRUST'
            enabled: true
            tags: ['POD01', 'POD02']
            profile: 'WITH_DHCP_01_SNOOPING'
          112:
            name: 'PR01-TRUST'
            enabled: true
            tags: ['POD01', 'POD02']
            ip_address_virtual: 10.1.12.254/24
            igmp_snooping_enabled: false
          113:
            name: 'PR01-DMZ'
            tags: [POD03]
            enabled: true
            ip_address_virtual: 10.1.13.254/24
            igmp_snooping_enabled: true
      #     311:
      #       name: 'PR01-TRUST-DHCP'
      #       tags: ['DC1']
      #       enabled: true
      #       ip_address_virtual: 10.3.11.254/24
      #       igmp_snooping_enabled: true
      #       ip_helpers:
      #         1.1.1.1:
      #           source_interface: lo100
      # TENANT_A_PROJECT02:
      #   ip_helpers:
      #     1.1.1.1:
      #       source_interface: lo100
      #   vrf_vni: 12
      #   vtep_diagnostic:
      #     loopback: 100
      #     loopback_ip_range: 10.2.255.0/24
      #   svis:
      #     114:
      #       name: 'PR02-DMZ'
      #       tags: ['POD01']
      #       enabled: true
      #       ip_address_virtual: 10.2.12.254/24
      #       igmp_snooping: true
      PURE_TYPE5:
        vrf_vni: 13
        svis:
          131:
            name: vl131_no_vni
            tags: ['POD01']
            enabled: true
            ip_address_virtual: 10.1.31.254/24
            vxlan: false
          132:
            name: vl132_no_vni
            tags: ['POD02']
            enabled: true
            ip_address_virtual: 10.1.32.254/24
            vxlan: false

# Tenant D Specific Information - Pure L2 tenant
  Tenant_B:
    mac_vrf_vni_base: 20000
    enable_mlag_ibgp_peering_vrfs: true
    l2vlans:
      201:
        name: 'B-ELAN-201'
        tags: ['DC1']
        igmp_snooping: false

  CENTRAL_ROUTING_LAB:
    mac_vrf_vni_base: 30000
    vrfs:
      CENTRAL_ROUTING:
        vrf_vni: 13
        svis:
          301:
            name: 'CENTRAL_LAN_01'
            tags: ['POD05_NODE01']
            enabled: true
            ip_address_virtual: 10.3.1.254/24
            # ip_virtual_router_address: 10.3.1.254
            # nodes:
            #   EAPI-CL01A:
            #     ip_address: 10.3.1.253/24
            #   EAPI-CL01B:
            #     ip_address: 10.3.1.252/24
          302:
            name: 'CENTRAL_LAN_02'
            tags: ['POD05_NODE02', 'POD05_NODE01']
            enabled: true
            ip_address_virtual: 10.3.2.254/24
            # ip_virtual_router_address: 10.3.2.254
            # nodes:
            #   EAPI-CL01A:
            #     ip_address: 10.3.2.253/24
            #   EAPI-CL01B:
            #     ip_address: 10.3.2.252/24

