vrfs:
  MGMT:
    ip_routing: false
  tenant_a_110:
    ip_routing: true
    ipv6_routing: false
  tenant_a_112:
    ip_routing: true
    ipv6_routing: false
  tenant_b_201:
    ip_routing: true
    ipv6_routing: false
  pure_type5:
    ip_routing: true
    ipv6_routing: false

ethernet_interfaces:
  Ethernet1:
    description:
    shutdown: false
    type: switched
    logging:
      event:
        link_status: true
    vlans: "1-4000"
    native_vlan: 1
    mode: trunk
    spanning_tree_bpdufilter: false
    spanning_tree_bpduguard: false
    spanning_tree_portfast: edge

vlan_interfaces:
  Vlan110:
    description: SVI for Tenant A vlan 110
    shutdown: false
    vrf: tenant_a_110
    ip_address: 10.1.10.2/24
  Vlan112:
    description: SVI for Tenant A vlan 112
    shutdown: false
    vrf: tenant_a_112
    ip_address: 10.1.12.2/24
  Vlan201:
    description: SVI for Tenant B vlan 201
    shutdown: false
    vrf: tenant_b_201
    ip_address: 10.2.1.2/24
  Vlan132:
    description: SVI for Pure Type 05 vlan 132
    shutdown: false
    vrf: pure_type5
    ip_address: 10.1.32.2/24

static_routes:
  - vrf: tenant_a_110
    destination_address_prefix: 0.0.0.0/0
    gateway: 10.1.10.254
  - vrf: tenant_a_112
    destination_address_prefix: 0.0.0.0/0
    gateway: 10.1.12.254
  - vrf: pure_type5
    destination_address_prefix: 0.0.0.0/0
    gateway: 10.1.32.254