---
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 10.73.254.253

service_routing_protocols_model: multi-agent

ip_routing: true

# daemon_terminattr:
#   ingestgrpcurl:
#     ips:
#     - 10.73.254.1
#     port: 9910
#   ingestvrf: MGMT
#   smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
#   ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
#   disable_aaa: false

vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199

name_server:
  source:
    vrf: MGMT
  nodes:
  - 10.73.254.253
  - 10.73.1.254

ntp_server:
  local_interface:
    vrf: MGMT
    interface: Management1
  nodes:
  - 10.73.254.253
  - 10.73.1.254

local_users:
  admin:
    privilege: 15
    role: network-admin
    no_password: true
  ansible:
    privilege: 15
    role: network-admin
    sha512_password: $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/
  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: $6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj.
  demo:
    privilege: 15
    role: network-admin
    sha512_password: $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/

clock:
  timezone: Europe/Paris

vrfs:
  MGMT:
    ip_routing: false

management_api_http:
  enable_vrfs:
    MGMT: {}
  enable_https: true

management_ssh:
  enable: true
  vrfs:
    MGMT:
      enable: true

management_console:
  idle_timeout: 0

aaa_authorization:
  exec:
    default: local

ip_igmp_snooping:
  globally_enabled: true

# errdisable:
#   recovery:
#     causes:
#       - bpduguard
#       - link-flap
#       - portchannelguard
#       - speed-misconfigured
#       - uplink-failure-detection
#   interval: 300
